#!/bin/sh

conda activate python2
# random snp
for species in conirostrum_bicolor conirostrum_margaritae cranioleuca_vulpecula dendroplex_kienerii elaenia_pelzelni furnarius_minor knipolegus_orenocensis leucippus_chlorocercus mazaria_propinqua myrmoborus_lugubris myrmochanes_hemileucus myrmotherula_assimilis myrmotherula_klagesi ochthornis_littoralis serpophaga_hypoleuca stigmatura_napensis thamnophilus thamnophilus_cryptoleucus thamnophilus_nigrocinereus Campephilus_melanoleucos Campephilus_rubricollis Cantorchilus_leucotis Celeus_flavus Celeus_grammicus Crypturellus_undulatus Crypturellus_variegatus Formicarius_analis Formicarius_colma Glaucidium_brasilianum Glaucidium_hardyi Hylophylax_naevia Hylophylax_punctulata Megascops_choliba Megascops_watsonii Monasa_morphoeus Monasa_nigrifrons Myrmeciza_fortis Myrmeciza_hyperythra Myrmoborus_leucophrys Myrmoborus_myotherinus Phaethornis_bourcieri Phaethornis_hispidus Pheugopedius_coraya Piaya_cayana Piaya_melanogaster Pipra_erythrocephala Pipra_filicauda Saltator_coerulescens Saltator_grossus Schiffornis_major Schiffornis_turdina Synallaxis_gujanensis Synallaxis_rutilans Tachyphonus_cristatus Tachyphonus_luctuosus Trogon_collaris Trogon_rufus Xiphorhynchus_elegans Xiphorhynchus_obsoletus
do

python /Users/mharvey/seqcap_pop-master/bin/genepop_from_vcf.py /Volumes/Brumfield_Lab_Drive/data/1_analysis/vcf_files_final_random_snp/${species}_SNPs_phased_rmIndels_75_QC_DP_random.recode.vcf /Volumes/Brumfield_Lab_Drive/data/1_analysis/genepop_final_random_snp/ ${species}_SNPs_phased_rmIndels_75_QC_DP_random --all

done


# all snps
for species in conirostrum_bicolor conirostrum_margaritae cranioleuca_vulpecula dendroplex_kienerii elaenia_pelzelni furnarius_minor knipolegus_orenocensis leucippus_chlorocercus mazaria_propinqua myrmoborus_lugubris myrmochanes_hemileucus myrmotherula_assimilis myrmotherula_klagesi ochthornis_littoralis serpophaga_hypoleuca stigmatura_napensis thamnophilus thamnophilus_cryptoleucus thamnophilus_nigrocinereus Campephilus_melanoleucos Campephilus_rubricollis Cantorchilus_leucotis Celeus_flavus Celeus_grammicus Crypturellus_undulatus Crypturellus_variegatus Formicarius_analis Formicarius_colma Glaucidium_brasilianum Glaucidium_hardyi Hylophylax_naevia Hylophylax_punctulata Megascops_choliba Megascops_watsonii Monasa_morphoeus Monasa_nigrifrons Myrmeciza_fortis Myrmeciza_hyperythra Myrmoborus_leucophrys Myrmoborus_myotherinus Phaethornis_bourcieri Phaethornis_hispidus Pheugopedius_coraya Piaya_cayana Piaya_melanogaster Pipra_erythrocephala Pipra_filicauda Saltator_coerulescens Saltator_grossus Schiffornis_major Schiffornis_turdina Synallaxis_gujanensis Synallaxis_rutilans Tachyphonus_cristatus Tachyphonus_luctuosus Trogon_collaris Trogon_rufus Xiphorhynchus_elegans Xiphorhynchus_obsoletus
do

python /Users/harveylab/Applications/seqcap_pop-master/bin/genepop_from_vcf.py /Volumes/Brumfield_Lab_Drive/River_islands/1_analysis/vcf_files_final_all_snps/${species}_SNPs_phased_rmIndels_75_QC_DP.recode.vcf /Volumes/Brumfield_Lab_Drive/River_islands/1_analysis/genepop_final_all_snps/ ${species}_SNPs_phased_rmIndels_75_QC_DP --all

done

conda deactivate


# python /Users/mharvey/seqcap_pop-master/bin/genepop_from_vcf.py /Volumes/Brumfield_Lab_Drive/data/1_analysis/vcf_files_final_random_snp/Campephilus_melanoleucos_SNPs_phased_rmIndels_75_QC_DP_random.recode.vcf /Volumes/Brumfield_Lab_Drive/data/1_analysis/genepop_final_random_snp/ Campephilus_melanoleucos_SNPs_phased_rmIndels_75_QC_DP_random --all
: '
python /Users/mharvey/seqcap_pop-master/bin/genepop_from_vcf.py \
	/Volumes/Brumfield_Lab_Drive/data/1_analysis/vcf_files_final_random_snp/${species}_SNPs_phased_rmIndels_75_QC_DP_random.recode.vcf \
	/Volumes/Brumfield_Lab_Drive/data/1_analysis/genepop_final_random_snp/ \
	${species}_SNPs_phased_rmIndels_75_QC_DP_random \
	--all
'
