#!/bin/bash

cd /Volumes/Brumfield_Lab_Drive/data/1_analysis/ 

# not working: elaenia_pelzelni
# done: cranioleuca_vulpecula conirostrum_margaritae conirostrum_bicolor myrmotherula_klagesi Xiphorhynchus_obsoletus
#for species in Campephilus_melanoleucos Campephilus_rubricollis Cantorchilus_leucotis Celeus_flavus  conirostrum_margaritae cranioleuca_vulpecula Crypturellus_undulatus Crypturellus_variegatus dendroplex_kienerii elaenia_pelzelni Formicarius_analis Formicarius_colma furnarius_minor Glaucidium_brasilianum Glaucidium_hardyi Hylophylax_naevia Hylophylax_punctulata knipolegus_orenocensis leucippus_chlorocercus mazaria_propinqua Megascops_choliba Megascops_watsonii Monasa_morphoeus Monasa_nigrifrons Myrmeciza_fortis Myrmeciza_hyperythra Myrmoborus_leucophrys myrmoborus_lugubris Myrmoborus_myotherinus myrmochanes_hemileucus myrmotherula_assimilis myrmotherula_klagesi ochthornis_littoralis Phaethornis_bourcieri Phaethornis_hispidus Pheugopedius_coraya Piaya_cayana Piaya_melanogaster Pipra_erythrocephala Pipra_filicauda Saltator_coerulescens Saltator_grossus Schiffornis_major Schiffornis_turdina serpophaga_hypoleuca stigmatura_napensis Synallaxis_gujanensis Synallaxis_rutilans Tachyphonus_cristatus Tachyphonus_luctuosus thamnophilus_cryptoleucus thamnophilus_nigrocinereus thamnophilus Trogon_collaris Trogon_rufus Xiphorhynchus_elegans Xiphorhynchus_obsoletus ; do
for species in furnarius_minor ; do
#for species in  cranioleuca_vulpecula elaenia_pelzelni furnarius_minor knipolegus_orenocensis leucippus_chlorocercus mazaria_propinqua myrmoborus_lugubris myrmochanes_hemileucus stigmatura_napensis thamnophilus_cryptoleucus Crypturellus_undulatus Formicarius_analis Formicarius_colma Monasa_nigrifrons Myrmeciza_fortis Myrmeciza_hyperythra Myrmoborus_leucophrys Pheugopedius_coraya Piaya_melanogaster Pipra_filicauda Schiffornis_major Schiffornis_turdina Tachyphonus_luctuosus Xiphorhynchus_elegans  ; do
	/Users/mharvey/src/sNMF_CL_v1.2/bin/vcf2geno \
		vcf_files_final_random_snp-for_geno_conversion/${species}_SNPs_phased_rmIndels_75_QC_DP_random.recode.vcf \
		geno_final_random_snp/${species}_SNPs_phased_rmIndels_75_QC_DP_random.geno

done

: '
# need to edit these vcfs. getting errors when converting to geno
knipolegus_orenocensis
leucippus_chlorocercus
mazaria_propinqua
myrmoborus_lugubris
myrmochanes_hemileucus
stigmatura_napensis
thamnophilus_cryptoleucus
Crypturellus_undulatus
Formicarius_analis
Formicarius_colma
Monasa_nigrifrons
Myrmeciza_fortis
Myrmeciza_hyperythra
Myrmoborus_leucophrys
Pheugopedius_coraya
Piaya_melanogaster
Pipra_filicauda
Schiffornis_major
Schiffornis_turdina
Tachyphonus_luctuosus
Xiphorhynchus_elegans
'